<?php
/**
 * 64 Districts of Bangladesh
 * Includes Bengali and English names, administrative division, geographic coordinates,
 * and official Islamic Foundation Bangladesh (IFB) prayer time minute offsets relative to Dhaka (base 0).
 */
return [
    // Dhaka Division
    [
        'id' => 1,
        'name_bn' => 'ঢাকা',
        'name_en' => 'Dhaka',
        'division_bn' => 'ঢাকা',
        'latitude' => 23.8103,
        'longitude' => 90.4125,
        'fajr_offset' => 0,
        'sunrise_offset' => 0,
        'dhuhr_offset' => 0,
        'asr_offset' => 0,
        'maghrib_offset' => 0,
        'isha_offset' => 0,
    ],
    [
        'id' => 2,
        'name_bn' => 'গাজীপুর',
        'name_en' => 'Gazipur',
        'division_bn' => 'ঢাকা',
        'latitude' => 24.0023,
        'longitude' => 90.4267,
        'fajr_offset' => 0,
        'sunrise_offset' => 0,
        'dhuhr_offset' => 0,
        'asr_offset' => 0,
        'maghrib_offset' => 0,
        'isha_offset' => 0,
    ],
    [
        'id' => 3,
        'name_bn' => 'নারায়ণগঞ্জ',
        'name_en' => 'Narayanganj',
        'division_bn' => 'ঢাকা',
        'latitude' => 23.6238,
        'longitude' => 90.5000,
        'fajr_offset' => -1,
        'sunrise_offset' => -1,
        'dhuhr_offset' => -1,
        'asr_offset' => -1,
        'maghrib_offset' => -1,
        'isha_offset' => -1,
    ],
    [
        'id' => 4,
        'name_bn' => 'টাঙ্গাইল',
        'name_en' => 'Tangail',
        'division_bn' => 'ঢাকা',
        'latitude' => 24.2513,
        'longitude' => 89.9167,
        'fajr_offset' => 2,
        'sunrise_offset' => 2,
        'dhuhr_offset' => 2,
        'asr_offset' => 2,
        'maghrib_offset' => 2,
        'isha_offset' => 2,
    ],
    [
        'id' => 5,
        'name_bn' => 'নরসিংদী',
        'name_en' => 'Narsingdi',
        'division_bn' => 'ঢাকা',
        'latitude' => 23.9322,
        'longitude' => 90.7154,
        'fajr_offset' => -2,
        'sunrise_offset' => -2,
        'dhuhr_offset' => -2,
        'asr_offset' => -2,
        'maghrib_offset' => -2,
        'isha_offset' => -2,
    ],
    [
        'id' => 6,
        'name_bn' => 'মানিকগঞ্জ',
        'name_en' => 'Manikganj',
        'division_bn' => 'ঢাকা',
        'latitude' => 23.8617,
        'longitude' => 90.0003,
        'fajr_offset' => 1,
        'sunrise_offset' => 1,
        'dhuhr_offset' => 1,
        'asr_offset' => 1,
        'maghrib_offset' => 1,
        'isha_offset' => 1,
    ],
    [
        'id' => 7,
        'name_bn' => 'মুন্সীগঞ্জ',
        'name_en' => 'Munshiganj',
        'division_bn' => 'ঢাকা',
        'latitude' => 23.5422,
        'longitude' => 90.5305,
        'fajr_offset' => -1,
        'sunrise_offset' => -1,
        'dhuhr_offset' => -1,
        'asr_offset' => -1,
        'maghrib_offset' => -1,
        'isha_offset' => -1,
    ],
    [
        'id' => 8,
        'name_bn' => 'ফরিদপুর',
        'name_en' => 'Faridpur',
        'division_bn' => 'ঢাকা',
        'latitude' => 23.6071,
        'longitude' => 89.8429,
        'fajr_offset' => 3,
        'sunrise_offset' => 3,
        'dhuhr_offset' => 3,
        'asr_offset' => 3,
        'maghrib_offset' => 3,
        'isha_offset' => 3,
    ],
    [
        'id' => 9,
        'name_bn' => 'রাজবাড়ী',
        'name_en' => 'Rajbari',
        'division_bn' => 'ঢাকা',
        'latitude' => 23.7574,
        'longitude' => 89.6445,
        'fajr_offset' => 4,
        'sunrise_offset' => 4,
        'dhuhr_offset' => 4,
        'asr_offset' => 4,
        'maghrib_offset' => 4,
        'isha_offset' => 4,
    ],
    [
        'id' => 10,
        'name_bn' => 'মাদারীপুর',
        'name_en' => 'Madaripur',
        'division_bn' => 'ঢাকা',
        'latitude' => 23.1641,
        'longitude' => 90.1897,
        'fajr_offset' => 1,
        'sunrise_offset' => 1,
        'dhuhr_offset' => 1,
        'asr_offset' => 1,
        'maghrib_offset' => 1,
        'isha_offset' => 1,
    ],
    [
        'id' => 11,
        'name_bn' => 'গোপালগঞ্জ',
        'name_en' => 'Gopalganj',
        'division_bn' => 'ঢাকা',
        'latitude' => 23.0051,
        'longitude' => 89.8266,
        'fajr_offset' => 3,
        'sunrise_offset' => 3,
        'dhuhr_offset' => 3,
        'asr_offset' => 3,
        'maghrib_offset' => 3,
        'isha_offset' => 3,
    ],
    [
        'id' => 12,
        'name_bn' => 'শরীয়তপুর',
        'name_en' => 'Shariatpur',
        'division_bn' => 'ঢাকা',
        'latitude' => 23.2423,
        'longitude' => 90.4348,
        'fajr_offset' => 0,
        'sunrise_offset' => 0,
        'dhuhr_offset' => 0,
        'asr_offset' => 0,
        'maghrib_offset' => 0,
        'isha_offset' => 0,
    ],
    [
        'id' => 13,
        'name_bn' => 'কিশোরগঞ্জ',
        'name_en' => 'Kishoreganj',
        'division_bn' => 'ঢাকা',
        'latitude' => 24.4449,
        'longitude' => 90.7766,
        'fajr_offset' => -2,
        'sunrise_offset' => -2,
        'dhuhr_offset' => -2,
        'asr_offset' => -2,
        'maghrib_offset' => -2,
        'isha_offset' => -2,
    ],

    // Chattogram Division
    [
        'id' => 14,
        'name_bn' => 'চট্টগ্রাম',
        'name_en' => 'Chattogram',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 22.3569,
        'longitude' => 91.7832,
        'fajr_offset' => -5,
        'sunrise_offset' => -5,
        'dhuhr_offset' => -5,
        'asr_offset' => -5,
        'maghrib_offset' => -5,
        'isha_offset' => -5,
    ],
    [
        'id' => 15,
        'name_bn' => 'কক্সবাজার',
        'name_en' => 'Cox\'s Bazar',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 21.4272,
        'longitude' => 92.0058,
        'fajr_offset' => -7,
        'sunrise_offset' => -7,
        'dhuhr_offset' => -7,
        'asr_offset' => -7,
        'maghrib_offset' => -7,
        'isha_offset' => -7,
    ],
    [
        'id' => 16,
        'name_bn' => 'কুমিল্লা',
        'name_en' => 'Cumilla',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 23.4682,
        'longitude' => 91.1788,
        'fajr_offset' => -3,
        'sunrise_offset' => -3,
        'dhuhr_offset' => -3,
        'asr_offset' => -3,
        'maghrib_offset' => -3,
        'isha_offset' => -3,
    ],
    [
        'id' => 17,
        'name_bn' => 'ফেনী',
        'name_en' => 'Feni',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 23.0159,
        'longitude' => 91.3976,
        'fajr_offset' => -4,
        'sunrise_offset' => -4,
        'dhuhr_offset' => -4,
        'asr_offset' => -4,
        'maghrib_offset' => -4,
        'isha_offset' => -4,
    ],
    [
        'id' => 18,
        'name_bn' => 'ব্রাহ্মণবাড়িয়া',
        'name_en' => 'Brahmanbaria',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 23.9571,
        'longitude' => 91.1115,
        'fajr_offset' => -3,
        'sunrise_offset' => -3,
        'dhuhr_offset' => -3,
        'asr_offset' => -3,
        'maghrib_offset' => -3,
        'isha_offset' => -3,
    ],
    [
        'id' => 19,
        'name_bn' => 'রাঙ্গামাটি',
        'name_en' => 'Rangamati',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 22.7324,
        'longitude' => 92.2985,
        'fajr_offset' => -7,
        'sunrise_offset' => -7,
        'dhuhr_offset' => -7,
        'asr_offset' => -7,
        'maghrib_offset' => -7,
        'isha_offset' => -7,
    ],
    [
        'id' => 20,
        'name_bn' => 'নোয়াখালী',
        'name_en' => 'Noakhali',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 22.8696,
        'longitude' => 91.0998,
        'fajr_offset' => -3,
        'sunrise_offset' => -3,
        'dhuhr_offset' => -3,
        'asr_offset' => -3,
        'maghrib_offset' => -3,
        'isha_offset' => -3,
    ],
    [
        'id' => 21,
        'name_bn' => 'চাঁদপুর',
        'name_en' => 'Chandpur',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 23.2333,
        'longitude' => 90.6667,
        'fajr_offset' => -1,
        'sunrise_offset' => -1,
        'dhuhr_offset' => -1,
        'asr_offset' => -1,
        'maghrib_offset' => -1,
        'isha_offset' => -1,
    ],
    [
        'id' => 22,
        'name_bn' => 'লক্ষ্মীপুর',
        'name_en' => 'Lakshmipur',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 22.9425,
        'longitude' => 90.8412,
        'fajr_offset' => -2,
        'sunrise_offset' => -2,
        'dhuhr_offset' => -2,
        'asr_offset' => -2,
        'maghrib_offset' => -2,
        'isha_offset' => -2,
    ],
    [
        'id' => 23,
        'name_bn' => 'খাগড়াছড়ি',
        'name_en' => 'Khagrachhari',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 23.1193,
        'longitude' => 91.9847,
        'fajr_offset' => -6,
        'sunrise_offset' => -6,
        'dhuhr_offset' => -6,
        'asr_offset' => -6,
        'maghrib_offset' => -6,
        'isha_offset' => -6,
    ],
    [
        'id' => 24,
        'name_bn' => 'বান্দরবান',
        'name_en' => 'Bandarban',
        'division_bn' => 'চট্টগ্রাম',
        'latitude' => 22.1953,
        'longitude' => 92.2184,
        'fajr_offset' => -7,
        'sunrise_offset' => -7,
        'dhuhr_offset' => -7,
        'asr_offset' => -7,
        'maghrib_offset' => -7,
        'isha_offset' => -7,
    ],

    // Rajshahi Division
    [
        'id' => 25,
        'name_bn' => 'রাজশাহী',
        'name_en' => 'Rajshahi',
        'division_bn' => 'রাজশাহী',
        'latitude' => 24.3745,
        'longitude' => 88.6042,
        'fajr_offset' => 7,
        'sunrise_offset' => 7,
        'dhuhr_offset' => 7,
        'asr_offset' => 7,
        'maghrib_offset' => 7,
        'isha_offset' => 7,
    ],
    [
        'id' => 26,
        'name_bn' => 'বগুড়া',
        'name_en' => 'Bogura',
        'division_bn' => 'রাজশাহী',
        'latitude' => 24.8465,
        'longitude' => 89.3730,
        'fajr_offset' => 4,
        'sunrise_offset' => 4,
        'dhuhr_offset' => 4,
        'asr_offset' => 4,
        'maghrib_offset' => 4,
        'isha_offset' => 4,
    ],
    [
        'id' => 27,
        'name_bn' => 'পাবনা',
        'name_en' => 'Pabna',
        'division_bn' => 'রাজশাহী',
        'latitude' => 24.0064,
        'longitude' => 89.2372,
        'fajr_offset' => 5,
        'sunrise_offset' => 5,
        'dhuhr_offset' => 5,
        'asr_offset' => 5,
        'maghrib_offset' => 5,
        'isha_offset' => 5,
    ],
    [
        'id' => 28,
        'name_bn' => 'সিরাজগঞ্জ',
        'name_en' => 'Sirajganj',
        'division_bn' => 'রাজশাহী',
        'latitude' => 24.4534,
        'longitude' => 89.7008,
        'fajr_offset' => 3,
        'sunrise_offset' => 3,
        'dhuhr_offset' => 3,
        'asr_offset' => 3,
        'maghrib_offset' => 3,
        'isha_offset' => 3,
    ],
    [
        'id' => 29,
        'name_bn' => 'নওগাঁ',
        'name_en' => 'Naogaon',
        'division_bn' => 'রাজশাহী',
        'latitude' => 24.7936,
        'longitude' => 88.9318,
        'fajr_offset' => 6,
        'sunrise_offset' => 6,
        'dhuhr_offset' => 6,
        'asr_offset' => 6,
        'maghrib_offset' => 6,
        'isha_offset' => 6,
    ],
    [
        'id' => 30,
        'name_bn' => 'নাটোর',
        'name_en' => 'Natore',
        'division_bn' => 'রাজশাহী',
        'latitude' => 24.4206,
        'longitude' => 88.9322,
        'fajr_offset' => 6,
        'sunrise_offset' => 6,
        'dhuhr_offset' => 6,
        'asr_offset' => 6,
        'maghrib_offset' => 6,
        'isha_offset' => 6,
    ],
    [
        'id' => 31,
        'name_bn' => 'চাঁপাইনবাবগঞ্জ',
        'name_en' => 'Chapainawabganj',
        'division_bn' => 'রাজশাহী',
        'latitude' => 24.5965,
        'longitude' => 88.2775,
        'fajr_offset' => 9,
        'sunrise_offset' => 9,
        'dhuhr_offset' => 9,
        'asr_offset' => 9,
        'maghrib_offset' => 9,
        'isha_offset' => 9,
    ],
    [
        'id' => 32,
        'name_bn' => 'জয়পুরহাট',
        'name_en' => 'Joypurhat',
        'division_bn' => 'রাজশাহী',
        'latitude' => 25.0968,
        'longitude' => 89.0227,
        'fajr_offset' => 5,
        'sunrise_offset' => 5,
        'dhuhr_offset' => 5,
        'asr_offset' => 5,
        'maghrib_offset' => 5,
        'isha_offset' => 5,
    ],

    // Khulna Division
    [
        'id' => 33,
        'name_bn' => 'খুলনা',
        'name_en' => 'Khulna',
        'division_bn' => 'খুলনা',
        'latitude' => 22.8456,
        'longitude' => 89.5403,
        'fajr_offset' => 4,
        'sunrise_offset' => 4,
        'dhuhr_offset' => 4,
        'asr_offset' => 4,
        'maghrib_offset' => 4,
        'isha_offset' => 4,
    ],
    [
        'id' => 34,
        'name_bn' => 'যশোর',
        'name_en' => 'Jashore',
        'division_bn' => 'খুলনা',
        'latitude' => 23.1664,
        'longitude' => 89.2182,
        'fajr_offset' => 5,
        'sunrise_offset' => 5,
        'dhuhr_offset' => 5,
        'asr_offset' => 5,
        'maghrib_offset' => 5,
        'isha_offset' => 5,
    ],
    [
        'id' => 35,
        'name_bn' => 'সাতক্ষীরা',
        'name_en' => 'Satkhira',
        'division_bn' => 'খুলনা',
        'latitude' => 22.7185,
        'longitude' => 89.0705,
        'fajr_offset' => 6,
        'sunrise_offset' => 6,
        'dhuhr_offset' => 6,
        'asr_offset' => 6,
        'maghrib_offset' => 6,
        'isha_offset' => 6,
    ],
    [
        'id' => 36,
        'name_bn' => 'কুষ্টিয়া',
        'name_en' => 'Kushtia',
        'division_bn' => 'খুলনা',
        'latitude' => 23.9013,
        'longitude' => 89.1204,
        'fajr_offset' => 5,
        'sunrise_offset' => 5,
        'dhuhr_offset' => 5,
        'asr_offset' => 5,
        'maghrib_offset' => 5,
        'isha_offset' => 5,
    ],
    [
        'id' => 37,
        'name_bn' => 'ঝিনাইদহ',
        'name_en' => 'Jhenaidah',
        'division_bn' => 'খুলনা',
        'latitude' => 23.5448,
        'longitude' => 89.1539,
        'fajr_offset' => 5,
        'sunrise_offset' => 5,
        'dhuhr_offset' => 5,
        'asr_offset' => 5,
        'maghrib_offset' => 5,
        'isha_offset' => 5,
    ],
    [
        'id' => 38,
        'name_bn' => 'বাগেরহাট',
        'name_en' => 'Bagerhat',
        'division_bn' => 'খুলনা',
        'latitude' => 22.6516,
        'longitude' => 89.7859,
        'fajr_offset' => 3,
        'sunrise_offset' => 3,
        'dhuhr_offset' => 3,
        'asr_offset' => 3,
        'maghrib_offset' => 3,
        'isha_offset' => 3,
    ],
    [
        'id' => 39,
        'name_bn' => 'চুয়াডাঙ্গা',
        'name_en' => 'Chuadanga',
        'division_bn' => 'খুলনা',
        'latitude' => 23.6402,
        'longitude' => 88.8418,
        'fajr_offset' => 7,
        'sunrise_offset' => 7,
        'dhuhr_offset' => 7,
        'asr_offset' => 7,
        'maghrib_offset' => 7,
        'isha_offset' => 7,
    ],
    [
        'id' => 40,
        'name_bn' => 'মেহেরপুর',
        'name_en' => 'Meherpur',
        'division_bn' => 'খুলনা',
        'latitude' => 23.7622,
        'longitude' => 88.6318,
        'fajr_offset' => 7,
        'sunrise_offset' => 7,
        'dhuhr_offset' => 7,
        'asr_offset' => 7,
        'maghrib_offset' => 7,
        'isha_offset' => 7,
    ],
    [
        'id' => 41,
        'name_bn' => 'নড়াইল',
        'name_en' => 'Narail',
        'division_bn' => 'খুলনা',
        'latitude' => 23.1725,
        'longitude' => 89.5127,
        'fajr_offset' => 4,
        'sunrise_offset' => 4,
        'dhuhr_offset' => 4,
        'asr_offset' => 4,
        'maghrib_offset' => 4,
        'isha_offset' => 4,
    ],
    [
        'id' => 42,
        'name_bn' => 'মাগুরা',
        'name_en' => 'Magura',
        'division_bn' => 'খুলনা',
        'latitude' => 23.4873,
        'longitude' => 89.4198,
        'fajr_offset' => 4,
        'sunrise_offset' => 4,
        'dhuhr_offset' => 4,
        'asr_offset' => 4,
        'maghrib_offset' => 4,
        'isha_offset' => 4,
    ],

    // Barishal Division
    [
        'id' => 43,
        'name_bn' => 'বরিশাল',
        'name_en' => 'Barishal',
        'division_bn' => 'বরিশাল',
        'latitude' => 22.7010,
        'longitude' => 90.3535,
        'fajr_offset' => 1,
        'sunrise_offset' => 1,
        'dhuhr_offset' => 1,
        'asr_offset' => 1,
        'maghrib_offset' => 1,
        'isha_offset' => 1,
    ],
    [
        'id' => 44,
        'name_bn' => 'পটুয়াখালী',
        'name_en' => 'Patuakhali',
        'division_bn' => 'বরিশাল',
        'latitude' => 22.3596,
        'longitude' => 90.3299,
        'fajr_offset' => 1,
        'sunrise_offset' => 1,
        'dhuhr_offset' => 1,
        'asr_offset' => 1,
        'maghrib_offset' => 1,
        'isha_offset' => 1,
    ],
    [
        'id' => 45,
        'name_bn' => 'ভোলা',
        'name_en' => 'Bhola',
        'division_bn' => 'বরিশাল',
        'latitude' => 22.6859,
        'longitude' => 90.6482,
        'fajr_offset' => -1,
        'sunrise_offset' => -1,
        'dhuhr_offset' => -1,
        'asr_offset' => -1,
        'maghrib_offset' => -1,
        'isha_offset' => -1,
    ],
    [
        'id' => 46,
        'name_bn' => 'পিরোজপুর',
        'name_en' => 'Pirojpur',
        'division_bn' => 'বরিশাল',
        'latitude' => 22.5841,
        'longitude' => 89.9720,
        'fajr_offset' => 2,
        'sunrise_offset' => 2,
        'dhuhr_offset' => 2,
        'asr_offset' => 2,
        'maghrib_offset' => 2,
        'isha_offset' => 2,
    ],
    [
        'id' => 47,
        'name_bn' => 'বরগুনা',
        'name_en' => 'Barguna',
        'division_bn' => 'বরিশাল',
        'latitude' => 22.0953,
        'longitude' => 90.1121,
        'fajr_offset' => 2,
        'sunrise_offset' => 2,
        'dhuhr_offset' => 2,
        'asr_offset' => 2,
        'maghrib_offset' => 2,
        'isha_offset' => 2,
    ],
    [
        'id' => 48,
        'name_bn' => 'ঝালকাঠি',
        'name_en' => 'Jhalokathi',
        'division_bn' => 'বরিশাল',
        'latitude' => 22.6406,
        'longitude' => 90.1987,
        'fajr_offset' => 1,
        'sunrise_offset' => 1,
        'dhuhr_offset' => 1,
        'asr_offset' => 1,
        'maghrib_offset' => 1,
        'isha_offset' => 1,
    ],

    // Sylhet Division
    [
        'id' => 49,
        'name_bn' => 'সিলেট',
        'name_en' => 'Sylhet',
        'division_bn' => 'সিলেট',
        'latitude' => 24.8949,
        'longitude' => 91.8687,
        'fajr_offset' => -6,
        'sunrise_offset' => -6,
        'dhuhr_offset' => -6,
        'asr_offset' => -6,
        'maghrib_offset' => -6,
        'isha_offset' => -6,
    ],
    [
        'id' => 50,
        'name_bn' => 'মৌলভীবাজার',
        'name_en' => 'Moulvibazar',
        'division_bn' => 'সিলেট',
        'latitude' => 24.4829,
        'longitude' => 91.7774,
        'fajr_offset' => -5,
        'sunrise_offset' => -5,
        'dhuhr_offset' => -5,
        'asr_offset' => -5,
        'maghrib_offset' => -5,
        'isha_offset' => -5,
    ],
    [
        'id' => 51,
        'name_bn' => 'হবিগঞ্জ',
        'name_en' => 'Habiganj',
        'division_bn' => 'সিলেট',
        'latitude' => 24.3749,
        'longitude' => 91.4155,
        'fajr_offset' => -4,
        'sunrise_offset' => -4,
        'dhuhr_offset' => -4,
        'asr_offset' => -4,
        'maghrib_offset' => -4,
        'isha_offset' => -4,
    ],
    [
        'id' => 52,
        'name_bn' => 'সুনামগঞ্জ',
        'name_en' => 'Sunamganj',
        'division_bn' => 'সিলেট',
        'latitude' => 25.0658,
        'longitude' => 91.3950,
        'fajr_offset' => -4,
        'sunrise_offset' => -4,
        'dhuhr_offset' => -4,
        'asr_offset' => -4,
        'maghrib_offset' => -4,
        'isha_offset' => -4,
    ],

    // Rangpur Division
    [
        'id' => 53,
        'name_bn' => 'রংপুর',
        'name_en' => 'Rangpur',
        'division_bn' => 'রংপুর',
        'latitude' => 25.7439,
        'longitude' => 89.2752,
        'fajr_offset' => 5,
        'sunrise_offset' => 5,
        'dhuhr_offset' => 5,
        'asr_offset' => 5,
        'maghrib_offset' => 5,
        'isha_offset' => 5,
    ],
    [
        'id' => 54,
        'name_bn' => 'দিনাজপুর',
        'name_en' => 'Dinajpur',
        'division_bn' => 'রংপুর',
        'latitude' => 25.6217,
        'longitude' => 88.6355,
        'fajr_offset' => 7,
        'sunrise_offset' => 7,
        'dhuhr_offset' => 7,
        'asr_offset' => 7,
        'maghrib_offset' => 7,
        'isha_offset' => 7,
    ],
    [
        'id' => 55,
        'name_bn' => 'গাইবান্ধা',
        'name_en' => 'Gaibandha',
        'division_bn' => 'রংপুর',
        'latitude' => 25.3288,
        'longitude' => 89.5407,
        'fajr_offset' => 4,
        'sunrise_offset' => 4,
        'dhuhr_offset' => 4,
        'asr_offset' => 4,
        'maghrib_offset' => 4,
        'isha_offset' => 4,
    ],
    [
        'id' => 56,
        'name_bn' => 'কুড়িগ্রাম',
        'name_en' => 'Kurigram',
        'division_bn' => 'রংপুর',
        'latitude' => 25.8054,
        'longitude' => 89.6362,
        'fajr_offset' => 3,
        'sunrise_offset' => 3,
        'dhuhr_offset' => 3,
        'asr_offset' => 3,
        'maghrib_offset' => 3,
        'isha_offset' => 3,
    ],
    [
        'id' => 57,
        'name_bn' => 'নীলফামারী',
        'name_en' => 'Nilphamari',
        'division_bn' => 'রংপুর',
        'latitude' => 25.9318,
        'longitude' => 88.8560,
        'fajr_offset' => 6,
        'sunrise_offset' => 6,
        'dhuhr_offset' => 6,
        'asr_offset' => 6,
        'maghrib_offset' => 6,
        'isha_offset' => 6,
    ],
    [
        'id' => 58,
        'name_bn' => 'লালমনিরহাট',
        'name_en' => 'Lalmonirhat',
        'division_bn' => 'রংপুর',
        'latitude' => 25.9923,
        'longitude' => 89.2847,
        'fajr_offset' => 4,
        'sunrise_offset' => 4,
        'dhuhr_offset' => 4,
        'asr_offset' => 4,
        'maghrib_offset' => 4,
        'isha_offset' => 4,
    ],
    [
        'id' => 59,
        'name_bn' => 'পঞ্চগড়',
        'name_en' => 'Panchagarh',
        'division_bn' => 'রংপুর',
        'latitude' => 26.3411,
        'longitude' => 88.5542,
        'fajr_offset' => 8,
        'sunrise_offset' => 8,
        'dhuhr_offset' => 8,
        'asr_offset' => 8,
        'maghrib_offset' => 8,
        'isha_offset' => 8,
    ],
    [
        'id' => 60,
        'name_bn' => 'ঠাকুরগাঁও',
        'name_en' => 'Thakurgaon',
        'division_bn' => 'রংপুর',
        'latitude' => 26.0337,
        'longitude' => 88.4617,
        'fajr_offset' => 8,
        'sunrise_offset' => 8,
        'dhuhr_offset' => 8,
        'asr_offset' => 8,
        'maghrib_offset' => 8,
        'isha_offset' => 8,
    ],

    // Mymensingh Division
    [
        'id' => 61,
        'name_bn' => 'ময়মনসিংহ',
        'name_en' => 'Mymensingh',
        'division_bn' => 'ময়মনসিংহ',
        'latitude' => 24.7471,
        'longitude' => 90.4203,
        'fajr_offset' => 0,
        'sunrise_offset' => 0,
        'dhuhr_offset' => 0,
        'asr_offset' => 0,
        'maghrib_offset' => 0,
        'isha_offset' => 0,
    ],
    [
        'id' => 62,
        'name_bn' => 'জামালপুর',
        'name_en' => 'Jamalpur',
        'division_bn' => 'ময়মনসিংহ',
        'latitude' => 24.9375,
        'longitude' => 89.9378,
        'fajr_offset' => 2,
        'sunrise_offset' => 2,
        'dhuhr_offset' => 2,
        'asr_offset' => 2,
        'maghrib_offset' => 2,
        'isha_offset' => 2,
    ],
    [
        'id' => 63,
        'name_bn' => 'নেত্রকোণা',
        'name_en' => 'Netrokona',
        'division_bn' => 'ময়মনসিংহ',
        'latitude' => 24.8709,
        'longitude' => 90.7279,
        'fajr_offset' => -1,
        'sunrise_offset' => -1,
        'dhuhr_offset' => -1,
        'asr_offset' => -1,
        'maghrib_offset' => -1,
        'isha_offset' => -1,
    ],
    [
        'id' => 64,
        'name_bn' => 'শেরপুর',
        'name_en' => 'Sherpur',
        'division_bn' => 'ময়মনসিংহ',
        'latitude' => 25.0205,
        'longitude' => 90.0153,
        'fajr_offset' => 2,
        'sunrise_offset' => 2,
        'dhuhr_offset' => 2,
        'asr_offset' => 2,
        'maghrib_offset' => 2,
        'isha_offset' => 2,
    ],
];
